### ISSUE TITLE
Failed to activate the gibber package

### ISSUE THREAD

**Issue by mgiglia** [charlieroberts/gibber.atom#1]
[Enter steps to reproduce below:]
1.  Installed the gibber package
2. Opened a new Atom file
3. Changed format to JavaScript
4. Selected packages -> gibber -> Toggle

(Restarted computer and received the same result with starting with step 2 above.  No other applications running.)

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [gibber](https://github.com/charlieroberts/gibber.atom) package, v0.1.3
### Stack Trace

Failed to activate the gibber package

```
At Identifier 'initSound' has already been declared

SyntaxError: Identifier 'initSound' has already been declared
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at module.exports (/Users/mgiglia/.atom/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio.js:7:17)
    at Object.<anonymous> (/Users/mgiglia/.atom/packages/gibber/lib/gibber.coffee:14:24)
    at Object.<anonymous> (/Users/mgiglia/.atom/packages/gibber/lib/gibber.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:718:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:798:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1109:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```
### Commands

```
     -0:11.1.0 application:open (atom-text-editor.editor.is-focused)
     -0:00.0 gibber:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
gibber, v0.1.3 (inactive)
language-sas, v0.2.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by robjac** [comment]
[Enter steps to reproduce below:]
1. open old gibber js file
2. went to pacakages, gibber, toggle

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [gibber](https://github.com/charlieroberts/gibber.atom) package, v0.1.3

### Stack Trace

Failed to activate the gibber package

```
At Identifier 'initSound' has already been declared

SyntaxError: Identifier 'initSound' has already been declared
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at module.exports (/Users/robjac/.atom/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio.js:7:17)
    at Object.<anonymous> (/Users/robjac/.atom/packages/gibber/lib/gibber.coffee:14:24)
    at Object.<anonymous> (/Users/robjac/.atom/packages/gibber/lib/gibber.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:718:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:798:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1109:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -0:41.6.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -0:41.1.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:40.1.0 core:select-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -0:39.6.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.linewise)
     -0:38.4.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.linewise.is-narrowed)
 22x -0:38.3.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  6x -0:35.9.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:33.5.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  8x -0:33 core:select-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:31.3.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.linewise)
     -0:31.3.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.linewise.is-narrowed)
     -0:29.9.0 sonic-pi-autocomplete:play-selection (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.linewise.is-narrowed)
     -0:28.4.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.linewise.is-narrowed)
     -0:24.5.0 core:close (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.characterwise)
     -0:22.1.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.tinted-tab-bar.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.paint-cursor.theme-hugs-syntax.theme-atom-material-ui.has-custom-icons)
     -0:00.0 gibber:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "settings-view",
      "term",
      "term3",
      "linter-sass-lint",
      "linter",
      "lint",
      "atom-autocomplete-php",
      "enhanced-package-list",
      "xkcd-comics",
      "activate-power-mode",
      "supercollider",
      "rails-snippets",
      "rails-partials",
      "project-viewer"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-material-ui",
      "hugs-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
activate-power-mode, v0.9.0 (inactive)
an-old-hope-syntax, v0.5.0 (inactive)
angularjs, v0.3.5 (active)
animated-cursor, v1.0.9 (active)
atom-autocomplete-php, v0.19.4 (inactive)
atom-beautify, v0.29.12 (inactive)
atom-handlebars, v1.3.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (active)
atom-monokai, v0.10.4 (inactive)
atom-monokai-dark, v0.4.0 (inactive)
atom-sonic, v0.3.2 (active)
auto-detect-indentation, v1.2.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-clang, v0.10.0 (active)
autocomplete-haskell, v0.6.7 (inactive)
autocomplete-java, v1.2.5 (inactive)
autocomplete-php, v0.3.7 (active)
autocomplete-ruby, v0.1.0 (active)
autoprefixer, v3.2.1 (inactive)
chameleon-dark-syntax, v0.0.5 (inactive)
color-picker, v2.2.2 (active)
ember-cli-helper, v0.9.0 (active)
emmet, v2.4.3 (active)
enhanced-package-list, v1.0.3 (inactive)
enhanced-tabs, v1.7.0 (inactive)
Extempore-Atom, v0.3.2 (inactive)
file-icons, v1.7.19 (active)
gibber, v0.1.3 (inactive)
git-projects, v1.17.0 (inactive)
git-status, v0.3.4 (inactive)
git-time-machine, v1.5.3 (inactive)
haskell-ghc-mod, v1.17.2 (inactive)
highlight-column, v0.5.1 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
hugs-syntax, v1.0.0 (active)
ide-haskell, v1.8.1 (inactive)
ide-haskell-cabal, v1.6.4 (inactive)
ide-haskell-hasktags, v0.0.6 (inactive)
ide-haskell-repl, v0.1.4 (inactive)
jquery-snippets, v11.0.0 (active)
KeyCount, v0.1.1 (inactive)
language-haml, v0.24.0 (active)
language-haskell, v1.9.9 (active)
lint, v0.0.1 (inactive)
linter, v1.11.16 (inactive)
linter-bootlint, v1.0.2 (active)
linter-clang, v3.4.4 (active)
linter-csslint, v1.3.2 (active)
linter-eslint, v7.3.2 (active)
linter-rubocop, v0.4.7 (active)
linter-sass-lint, v1.7.1 (inactive)
linter-scss-lint, v3.0.4 (active)
lunar-particle-syntax, v0.3.8 (inactive)
lunar-particle-ui, v0.3.13 (inactive)
minimap, v4.25.0 (active)
minimap-autohide, v0.10.1 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-pigments, v0.2.1 (active)
minimap-selection, v4.4.0 (active)
monokai, v0.18.0 (inactive)
monokai-dark, v1.3.0 (inactive)
monokai-flat, v1.0.1 (inactive)
monokai-seti, v0.7.0 (inactive)
neon-syntax, v0.3.6 (inactive)
nucleus-dark-ui, v0.9.5 (inactive)
octocat-syntax, v0.1.5 (inactive)
open-recent, v5.0.0 (active)
package-cop, v0.2.10 (active)
package-list, v0.1.2 (inactive)
package-switch, v0.5.0 (active)
package-sync, v1.1.0 (active)
pigments, v0.35.0 (active)
project-colorize, v0.2.0 (active)
project-manager, v3.2.3 (active)
project-sidebar, v1.3.0 (inactive)
project-view, v0.6.1 (active)
project-viewer, v0.3.23 (inactive)
rails-finder, v0.7.0 (inactive)
rails-partials, v0.9.2 (inactive)
rails-snippets, v2.8.0 (inactive)
recent-projects, v0.13.0 (active)
robin-hood-syntax, v1.0.0 (inactive)
rubocop-auto-correct, v1.5.1 (inactive)
selector-to-tag, v0.4.1 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
SkriptDark-Neon-Syntax, v2.1.2 (inactive)
sonic-pi-autocomplete, v2.0.12 (active)
spacegray-dark-syntax, v0.2.0 (inactive)
steam-pirate-syntax, v0.3.0 (inactive)
steam-pirate-ui, v0.6.1 (inactive)
supercollider, v0.7.2 (inactive)
tab-smart-sort, v0.1.4 (active)
term, v0.2.4 (inactive)
term3, v0.22.1 (inactive)
terminal-plus, v0.14.5 (active)
tidalcycles, v0.8.4 (inactive)
todo-show, v1.7.0 (inactive)
tree-view-git-status, v1.1.0 (active)
vertical-tabs, v0.4.1 (active)
vim-mode-plus, v0.57.0 (active)
vivid, v1.1.8 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Nfinished** [comment]
+1

**Comment by mikesimmonds** [comment]
+1 on Atom 1.10.2 under Ubuntu 16.04

**Comment by failoften** [comment]
+1

**Comment by failoften** [comment]
++

**Comment by reubenjelleyman** [comment]
+1 on Atom 1.27.2 on macOS HS
