### ISSUE TITLE
Uncaught SyntaxError: Identifier 'initSound' has already been declared

### ISSUE THREAD

**Issue by bernatferragut** [charlieroberts/gibber.atom#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [gibber](https://github.com/charlieroberts/gibber.atom) package 0.1.3

### Stack Trace

Uncaught SyntaxError: Identifier 'initSound' has already been declared

```
At /Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:97

SyntaxError: Identifier 'initSound' has already been declared
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at module.exports (/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio.js:7:17)
    at /packages/gibber/lib/gibber.coffee:14:24)
    at /packages/gibber/lib/gibber.coffee:2:1)
    at /packages/gibber/lib/gibber.coffee:2:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:301:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:793:40)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:438:22)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:430:18)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:727:22
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:810:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:703:33)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:542:32
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -0:51.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
gibber 0.1.3 
```

**Comment by digitalohm** [comment]
Steps to reproduce:

Installed gibber from within Atom

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [gibber](https://github.com/charlieroberts/gibber.atom) package 0.1.3


### Stack Trace

Uncaught SyntaxError: Identifier 'initSound' has already been declared

```
At C:\Users\digitalohm\AppData\Local\atom\app-1.24.0\resources\app\src\native-compile-cache.js:97

SyntaxError: Identifier 'initSound' has already been declared
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.24.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:66:33)
    at module.exports (/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio.js:7:17)
    at /packages/gibber/lib/gibber.coffee:14:24)
    at /packages/gibber/lib/gibber.coffee:2:1)
    at /packages/gibber/lib/gibber.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.24.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.24.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:782:33)
    at Package.activateConfig (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:267:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-card.js:793:40)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-card.js:438:22)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-card.js:430:18)
    at ~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-card.js:727:22
    at ~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-card.js:810:17
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-manager.js:703:33)
    at ~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-manager.js:542:32
    at exit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.24.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.24.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -6:51.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
gibber 0.1.3 
language-powershell 4.0.0 
```
