### ISSUE TITLE
Uncaught TypeError: Cannot read property 'time' of undefined

### ISSUE THREAD

**Issue by trenchmortar** [charlieroberts/gibber.atom#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04.1
**Thrown From**: [gibber](https://github.com/charlieroberts/gibber.atom) package 0.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'time' of undefined

```
At /home/trenchmortar1/.atom/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio/seq.js:213

TypeError: Cannot read property 'time' of undefined
    at Object.Seq (/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio/seq.js:213:37)
    at Object.defineSequencedProperty (/packages/gibber/node_modules/gibber.core.lib/scripts/gibber.js:424:35)
    at Object.defineProperty (/packages/gibber/node_modules/gibber.core.lib/scripts/gibber.js:729:29)
    at Object.createProxyProperty (/packages/gibber/node_modules/gibber.core.lib/scripts/gibber.js:751:12)
    at Object.createProxyProperties (/packages/gibber/node_modules/gibber.core.lib/scripts/gibber.js:766:16)
    at ugen.start (/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio/clock.js:131:14)
    at Object.Audio.Core.onstart (/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio.js:78:19)
    at start (/packages/gibber/node_modules/gibberish-dsp/build/gibberish.js:361:41)
```

### Commands

```
  4x -0:29.9.0 core:backspace (input.hidden-input)
     -0:20 gibber:toggle (input.hidden-input)
```

### Non-Core Packages

```
gibber 0.1.3 
```

**Comment by magfoto** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [gibber](https://github.com/charlieroberts/gibber.atom) package 0.1.3


### Stack Trace

Uncaught TypeError: Cannot read property 'time' of undefined

```
At /Users/magfoto/.atom/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio/seq.js:213

TypeError: Cannot read property 'time' of undefined
    at Object.Seq (/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio/seq.js:213:37)
    at Object.defineSequencedProperty (/packages/gibber/node_modules/gibber.core.lib/scripts/gibber.js:424:35)
    at Object.defineProperty (/packages/gibber/node_modules/gibber.core.lib/scripts/gibber.js:729:29)
    at Object.createProxyProperty (/packages/gibber/node_modules/gibber.core.lib/scripts/gibber.js:751:12)
    at Object.createProxyProperties (/packages/gibber/node_modules/gibber.core.lib/scripts/gibber.js:766:16)
    at ugen.start (/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio/clock.js:131:14)
    at Object.Audio.Core.onstart (/packages/gibber/node_modules/gibber.audio.lib/scripts/gibber/audio.js:78:19)
    at start (/packages/gibber/node_modules/gibberish-dsp/build/gibberish.js:361:41)
```

### Commands

```
  2x -1:15.7.0 grammar-selector:show (ul.list-inline.tab-bar.inset-panel)
     -0:38.1.0 gibber:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.2.16 
atom-sonic 0.3.2 
gibber 0.1.3 
platformio-ide-terminal 2.10.0 
tidalcycles 3.10.1 
web-audio-api-snippets 1.3.0 
```
